"""The Alembic migration: round trip on a fresh database, and no drift.

These tests are synchronous on purpose. ``alembic/env.py`` drives its async
engine with ``asyncio.run()``, which cannot be called from inside a running
event loop, so the migration is exercised through ``alembic.command`` in a sync
test instead of the async ``database`` fixture.
"""

from itertools import pairwise
from pathlib import Path

import pytest
import sqlalchemy as sa
from alembic.autogenerate import compare_metadata
from alembic.config import Config
from alembic.migration import MigrationContext
from alembic.script import ScriptDirectory
from alembic.util import AutogenerateDiffsDetected

from alembic import command
from app.core.config import Settings
from app.models import Base

BACKEND_DIR = Path(__file__).resolve().parents[2]

SCHEMA_TABLES = {
    "users",
    "consents",
    "chat_sessions",
    "messages",
    "mood_entries",
    "journal_entries",
    "assessment_results",
    "safety_events",
    "refresh_tokens",
}


def _alembic_config() -> Config:
    """An alembic Config pointing at backend/alembic.ini and its script dir."""
    config = Config(str(BACKEND_DIR / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND_DIR / "alembic"))
    return config


def _database_file(settings: Settings) -> Path:
    return Path(sa.make_url(settings.database_url).database or "")


def _tables(settings: Settings) -> set[str]:
    url = settings.database_url
    engine = sa.create_engine(sa.make_url(url).set(drivername="sqlite"))
    try:
        return set(sa.inspect(engine).get_table_names())
    finally:
        engine.dispose()


def test_the_repository_ships_one_root_revision() -> None:
    script = ScriptDirectory(str(BACKEND_DIR / "alembic"))
    revisions = list(script.walk_revisions())
    roots = [rev for rev in revisions if rev.down_revision is None]
    assert [rev.revision for rev in roots] == ["0001"]
    # Linear history, newest first: each revision revises the one below it.
    for newer, older in pairwise(revisions):
        assert newer.down_revision == older.revision


def test_upgrade_downgrade_upgrade_on_a_fresh_database(settings: Settings) -> None:
    config = _alembic_config()
    head = str(ScriptDirectory(str(BACKEND_DIR / "alembic")).get_current_head())
    database_file = _database_file(settings)
    assert not database_file.exists(), "the test database must start out absent"

    command.upgrade(config, "head")
    assert _tables(settings) >= SCHEMA_TABLES
    assert _revision(settings) == head

    command.downgrade(config, "base")
    # Only alembic's own bookkeeping survives a full downgrade.
    assert _tables(settings) == {"alembic_version"}
    assert _revision(settings) is None

    command.upgrade(config, "head")
    assert _tables(settings) >= SCHEMA_TABLES
    assert _revision(settings) == head


def test_upgrade_is_idempotent_and_creates_the_indexes(settings: Settings) -> None:
    config = _alembic_config()
    command.upgrade(config, "head")
    command.upgrade(config, "head")  # no error when already at head
    engine = sa.create_engine(sa.make_url(settings.database_url).set(drivername="sqlite"))
    try:
        inspector = sa.inspect(engine)
        indexed = {
            index["name"]
            for table in inspector.get_table_names()
            for index in inspector.get_indexes(table)
        }
    finally:
        engine.dispose()
    assert {
        "ix_consents_user_id_created_at",
        "ix_chat_sessions_user_id_created_at",
        "ix_messages_session_id_created_at",
        "ix_mood_entries_user_id_created_at",
        "ix_journal_entries_user_id_created_at",
        "ix_assessment_results_user_id_created_at",
        "ix_safety_events_user_id_created_at",
        "ix_safety_events_session_id_created_at",
    } <= indexed


def test_migration_and_models_do_not_drift(settings: Settings) -> None:
    """`alembic check` for CI: autogenerate must find nothing to add or change."""
    config = _alembic_config()
    command.upgrade(config, "head")
    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - only on drift
        pytest.fail(f"model/migration drift detected: {exc}")


def test_autogenerate_diff_is_empty(settings: Settings) -> None:
    """The same comparison, inspectable: an empty diff list, not just no raise."""
    command.upgrade(_alembic_config(), "head")
    engine = sa.create_engine(sa.make_url(settings.database_url).set(drivername="sqlite"))
    try:
        with engine.connect() as connection:
            context = MigrationContext.configure(connection)
            diff = compare_metadata(context, Base.metadata)
    finally:
        engine.dispose()
    assert diff == []


def _revision(settings: Settings) -> str | None:
    engine = sa.create_engine(sa.make_url(settings.database_url).set(drivername="sqlite"))
    try:
        with engine.connect() as connection:
            rows = connection.execute(sa.text("SELECT version_num FROM alembic_version")).all()
        return None if not rows else str(rows[0][0])
    except sa.exc.OperationalError:  # pragma: no cover - no table yet
        return None
    finally:
        engine.dispose()
