/**
 * Onboarding copy.
 *
 * Tone rules (AGENTS.md): warm, plain, short, non-judgemental, no toxic
 * positivity. Nothing here promises an outcome, and nothing claims Manovia is a
 * person or a clinician.
 *
 * The AI-disclosure text and the consent versions are *fallbacks*: the server is
 * the source of truth (`GET /api/v1/consent/requirements`), and
 * `src/onboarding/content.test.ts` fails if these copies drift from
 * `backend/app/content/consent_documents.json`.
 */

import type { ConsentKind } from "@/lib/endpoints";

export const FALLBACK_CONSENT_VERSION = "2026-10-01";

export const FALLBACK_AI_DISCLOSURE =
  "Manovia is an AI-powered self-help companion. The replies you get are generated by an AI, " +
  "not written by a human therapist or counsellor. It cannot diagnose you, cannot give medical " +
  "or medication advice, and is not an emergency or crisis service — if you are in danger or " +
  "thinking about harming yourself, please contact your local emergency services or a helpline " +
  "right away. Sharing how you feel can still help you reflect and feel less alone. You are in " +
  "control: you choose what to write, you can stop at any time, and you can delete your account " +
  "and its data whenever you want.";

export const WELCOME_COPY = {
  heading: "Welcome to Manovia",
  intro:
    "A quiet place to notice how you are doing, one small step at a time. Nothing here is shared with anyone else unless you choose to.",
  points: [
    "Write about your day, or just sit with a prompt.",
    "Track your mood and see gentle patterns over time.",
    "Try short exercises when things feel heavy.",
  ],
  reassurance:
    "You can stop at any point, and you can delete your account and everything in it whenever you want.",
} as const;

export const SCOPE_COPY = {
  heading: "What Manovia is — and is not",
  intro: "Being clear about this matters more than any feature, so it comes before anything else.",
  is: [
    "A self-help companion for everyday ups and downs.",
    "Software that runs on an AI model, with written safety rules around it.",
    "Private by default: your words are encrypted, and never sold.",
    "Yours to control — export, pause, or delete at any time.",
  ],
  isNot: [
    "Not therapy, counselling, or any kind of treatment.",
    "Not a diagnosis, and never a substitute for a professional who knows you.",
    "Not a crisis service. It cannot send help to you.",
    "Not a person. There is no one on the other side reading your messages.",
  ],
} as const;

export const AI_DISCLOSURE_COPY = {
  heading: "Before we start: this is an AI",
  intro:
    "You deserve to know exactly what you are talking to. Here is Manovia's AI disclosure, word for word.",
} as const;

export interface ConsentCopy {
  title: string;
  summary: string;
  required: boolean;
}

/** Shown until (or instead of) the server's document set. */
export const CONSENT_COPY: Record<ConsentKind, ConsentCopy> = {
  terms: {
    title: "Terms of use",
    summary:
      "You are in charge of your account and your entries, you must be old enough to consent in your country, and Manovia is a self-help companion — not therapy, not a diagnosis, and not a crisis service.",
    required: true,
  },
  privacy: {
    title: "Privacy policy",
    summary:
      "What we store (your account, your entries, safety metadata) and why. Chat, journal and mood text is encrypted at rest, is never sold, and can be erased by deleting your account.",
    required: true,
  },
  ai_disclosure: {
    title: "AI disclosure",
    summary: "Manovia is software, not a person. What you read here is generated by an AI.",
    required: true,
  },
  store_chat: {
    title: "Store my chat history",
    summary:
      "Optional: let Manovia keep your conversations so you can look back at them. The text is stored encrypted, and withdrawing this consent stops future storage.",
    required: false,
  },
};

export const CONSENT_COPY_NOTE =
  "Each box is separate and starts unticked. You choose. Only the first three are needed to use Manovia.";
